# Generated by Django 5.1.3 on 2024-11-11 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
